blank_issues_enabled: false
contact_links:
  - name: Payara Community Forum
    url: http://www.payara.org/forum
    about: Please ask and answer questions about the Payara Platform here.
  - name: Security Issue Report
    url: mailto:security@payara.fish
    about: Report security vulnerabilities and flaws
